[package]
authors = ["David Peter <mail@david-peter.de>"]
categories = ["command-line-utilities"]
description = "A command-line benchmarking tool"
homepage = "https://github.com/sharkdp/hyperfine"
license = "MIT/Apache-2.0"
name = "hyperfine"
readme = "README.md"
repository = "https://github.com/sharkdp/hyperfine"
version = "0.3.0"

[dependencies]
ansi_term = "0.10"
indicatif = "0.9"
statistical = "0.1"
libc = "0.2"
atty = "0.2.2"

[dependencies.clap]
version = "2"
default-features = false
features = ["suggestions", "color", "wrap_help"]

[dev-dependencies]
approx = "0.1.1"
